import React, { useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { RotateCcw, Edit3, ChevronRight, Info, Download, Upload, Share2, Users, Tag } from 'lucide-react';
import { motion } from 'motion/react';
import { Capacitor } from '@capacitor/core';
import { Share } from '@capacitor/share';
import { Directory, Filesystem } from '@capacitor/filesystem';
import { Expense, TripData, TripSetup } from '../utils/calculations.ts';
import { formatCurrency } from '../utils/cn';

interface SettingsProps {
  onReset: () => void;
  data: TripData;
  onImport: (setup: TripSetup, expenses: Expense[]) => void;
}

const blobToBase64 = (blob: Blob): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error('Failed to read image.'));
    reader.onloadend = () => {
      if (typeof reader.result !== 'string') { reject(new Error('Invalid image data.')); return; }
      const idx = reader.result.indexOf(',');
      resolve(idx >= 0 ? reader.result.slice(idx + 1) : reader.result);
    };
    reader.readAsDataURL(blob);
  });

export const Settings: React.FC<SettingsProps> = ({ onReset, data, onImport }) => {
  const navigate = useNavigate();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const totalBudget = data.setup?.totalBudget ?? 0;
  const totalSpent = data.expenses.reduce((s, e) => s + e.amount, 0);

  const handleReset = () => {
    if (window.confirm('Reset the trip? This will delete all expenses and setup data.')) {
      onReset();
      navigate('/setup');
    }
  };

  const handleShare = async () => {
    const remaining = totalBudget - totalSpent;
    const catTotals = data.expenses.reduce((acc, exp) => {
      acc[exp.category] = (acc[exp.category] || 0) + exp.amount;
      return acc;
    }, {} as Record<string, number>);

    let text = `📊 *TripSpend Summary*\n\n`;
    text += `💰 Budget: ${formatCurrency(totalBudget)}\n`;
    text += `💸 Spent: ${formatCurrency(totalSpent)}\n`;
    text += `🏦 Remaining: ${formatCurrency(remaining)}\n\n`;
    text += `*By Category:*\n`;
    Object.entries(catTotals).forEach(([cat, amt]) => { text += `- ${cat}: ${formatCurrency(amt)}\n`; });
    text += `\n_Generated by TripSpend_`;

    if (navigator.share) {
      await navigator.share({ title: 'TripSpend Summary', text }).catch(() => {});
    } else {
      await navigator.clipboard.writeText(text);
      alert('Summary copied to clipboard!');
    }
  };

  const handleShareImage = async () => {
    const remaining = totalBudget - totalSpent;
    const canvas = document.createElement('canvas');
    canvas.width = 1080; canvas.height = 1350;
    const ctx = canvas.getContext('2d');
    if (!ctx) { alert('Could not generate image.'); return; }

    ctx.fillStyle = '#f8fafc'; ctx.fillRect(0, 0, 1080, 1350);
    ctx.fillStyle = '#2563eb'; ctx.fillRect(70, 70, 940, 220);
    ctx.fillStyle = '#fff'; ctx.font = 'bold 58px sans-serif';
    ctx.fillText('TripSpend Summary', 110, 180);
    ctx.fillStyle = '#0f172a'; ctx.font = 'bold 46px sans-serif';
    ctx.fillText(`Budget: Rs ${totalBudget.toFixed(0)}`, 110, 380);
    ctx.fillText(`Spent: Rs ${totalSpent.toFixed(0)}`, 110, 460);
    ctx.fillText(`Remaining: Rs ${remaining.toFixed(0)}`, 110, 540);

    const catTotals = data.expenses.reduce((acc, exp) => {
      acc[exp.category] = (acc[exp.category] || 0) + exp.amount;
      return acc;
    }, {} as Record<string, number>);
    ctx.font = 'bold 38px sans-serif'; ctx.fillText('Category Breakdown', 110, 660);
    ctx.font = '32px sans-serif';
    let y = 740;
    Object.entries(catTotals).forEach(([cat, amt]) => { ctx.fillText(`${cat}: Rs ${amt.toFixed(0)}`, 110, y); y += 64; });
    ctx.fillStyle = '#475569'; ctx.font = '26px sans-serif';
    ctx.fillText(`Generated on ${new Date().toLocaleDateString()}`, 110, 1240);

    const blob = await new Promise<Blob | null>(res => canvas.toBlob(res, 'image/png'));
    if (!blob) { alert('Could not generate image.'); return; }

    const fileName = `tripspend_summary_${Date.now()}.png`;
    const file = new File([blob], fileName, { type: 'image/png' });

    if (Capacitor.isNativePlatform()) {
      try {
        const b64 = await blobToBase64(blob);
        const result = await Filesystem.writeFile({ path: fileName, data: b64, directory: Directory.Cache });
        await Share.share({ title: 'TripSpend Summary', files: [result.uri], dialogTitle: 'Share summary' });
        return;
      } catch { /* fall through */ }
    }

    if (navigator.share && navigator.canShare?.({ files: [file] })) {
      try { await navigator.share({ title: 'TripSpend Summary', files: [file] }); return; } catch { /* fall through */ }
    }

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = fileName; a.click();
    URL.revokeObjectURL(url);
  };

  const handleExport = () => {
    const uri = 'data:application/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(data, null, 2));
    const date = new Date().toISOString().split('T')[0];
    const a = document.createElement('a');
    a.setAttribute('href', uri);
    a.setAttribute('download', `tripspend_backup_${date}.json`);
    a.click();
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const parsed = JSON.parse(ev.target?.result as string);
        if (parsed.setup && Array.isArray(parsed.expenses)) {
          onImport(parsed.setup, parsed.expenses);
          alert('Backup restored!');
          navigate('/');
        } else { alert('Invalid backup file.'); }
      } catch { alert('Could not read backup file.'); }
    };
    reader.readAsText(file);
  };

  return (
    <div className="page-shell space-y-6">
      <div className="page-header">
        <h1 className="page-title">Settings</h1>
        <p className="page-subtitle">Manage your trip</p>
      </div>

      {/* Trip */}
      <Section label="Trip">
        <SettingItem icon={<Edit3 className="w-4.5 h-4.5 text-blue-600" />} iconBg="bg-blue-50"
          label="Edit Trip Setup" description="Budget, dates, people"
          onClick={() => navigate('/setup')} />
        <Divider />
        <SettingItem icon={<Users className="w-4.5 h-4.5 text-teal-600" />} iconBg="bg-teal-50"
          label="Manage Members" description="Add or rename participants"
          onClick={() => navigate('/members')} />
        <Divider />
        <SettingItem icon={<Tag className="w-4.5 h-4.5 text-rose-600" />} iconBg="bg-rose-50"
          label="Manage Categories" description="Customise expense categories"
          onClick={() => navigate('/categories')} />
      </Section>

      {/* Share */}
      <Section label="Share">
        <SettingItem icon={<Share2 className="w-4.5 h-4.5 text-emerald-600" />} iconBg="bg-emerald-50"
          label="Share Summary" description="Send trip summary via WhatsApp"
          onClick={handleShare} />
        <Divider />
        <SettingItem icon={<Share2 className="w-4.5 h-4.5 text-indigo-600" />} iconBg="bg-indigo-50"
          label="Share Summary Image" description="Generate a shareable summary card"
          onClick={() => { void handleShareImage(); }} />
      </Section>

      {/* Data */}
      <Section label="Data">
        <SettingItem icon={<Download className="w-4.5 h-4.5 text-purple-600" />} iconBg="bg-purple-50"
          label="Export Backup" description="Save all data as JSON"
          onClick={handleExport} />
        <Divider />
        <SettingItem icon={<Upload className="w-4.5 h-4.5 text-amber-600" />} iconBg="bg-amber-50"
          label="Import Backup" description="Restore from a JSON backup"
          onClick={() => fileInputRef.current?.click()} />
        <input ref={fileInputRef} type="file" accept=".json" className="hidden" onChange={handleImport} />
      </Section>

      {/* Danger */}
      <Section label="Danger Zone">
        <SettingItem icon={<RotateCcw className="w-4.5 h-4.5 text-red-600" />} iconBg="bg-red-50"
          label="Reset Trip" description="Delete all data and start fresh"
          onClick={handleReset} danger />
      </Section>

      {/* About */}
      <div className="bg-white rounded-3xl border border-slate-100 shadow-sm p-5 text-center space-y-1">
        <p className="font-black text-slate-900 text-lg">TripSpend</p>
        <p className="text-xs text-slate-400">Made by Amartya Vishwakarma</p>
        <p className="text-xs text-slate-300 font-bold uppercase tracking-widest pt-2">v1.0.0</p>
      </div>
    </div>
  );
};

const Section: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => (
  <div>
    <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-2 px-1">{label}</p>
    <div className="bg-white rounded-3xl border border-slate-100 shadow-sm overflow-hidden">
      {children}
    </div>
  </div>
);

const Divider = () => <div className="h-px bg-slate-50 mx-5" />;

const SettingItem = ({ icon, iconBg, label, description, onClick, danger }: {
  icon: React.ReactNode;
  iconBg: string;
  label: string;
  description: string;
  onClick: () => void;
  danger?: boolean;
}) => (
  <motion.button
    whileTap={{ scale: 0.98 }}
    onClick={onClick}
    className="w-full px-5 py-4 flex items-center gap-4 hover:bg-slate-50 transition-colors text-left group"
  >
    <div className={`w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 ${iconBg}`}>
      {icon}
    </div>
    <div className="flex-1 min-w-0">
      <p className={`font-semibold text-sm leading-tight ${danger ? 'text-red-600' : 'text-slate-900'}`}>{label}</p>
      <p className="text-xs text-slate-400 mt-0.5">{description}</p>
    </div>
    <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-slate-400 group-hover:translate-x-0.5 transition-all flex-shrink-0" />
  </motion.button>
);
