import React, { useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Settings as SettingsIcon, RotateCcw, Edit3, ChevronRight, Info, Download, Upload, Share2, Image as ImageIcon, BarChart3, Users, Tag } from 'lucide-react';
import { motion } from 'motion/react';
import { Capacitor } from '@capacitor/core';
import { Share } from '@capacitor/share';
import { Directory, Filesystem } from '@capacitor/filesystem';
import { Expense, TripData, TripSetup } from '../utils/calculations.ts';

interface SettingsProps {
  onReset: () => void;
  data: TripData;
  onImport: (setup: TripSetup, expenses: Expense[]) => void;
}

const blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error('Failed to read summary image.'));
    reader.onloadend = () => {
      if (typeof reader.result !== 'string') {
        reject(new Error('Invalid image data.'));
        return;
      }

      const commaIndex = reader.result.indexOf(',');
      resolve(commaIndex >= 0 ? reader.result.slice(commaIndex + 1) : reader.result);
    };
    reader.readAsDataURL(blob);
  });
};

export const Settings: React.FC<SettingsProps> = ({ onReset, data, onImport }) => {
  const navigate = useNavigate();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const getTotalBudget = () => {
    if (!data.setup) return 0;

    const setup = data.setup as TripSetup & { perPersonBudget?: number };
    const direct = Number(setup.totalBudget);
    if (Number.isFinite(direct) && direct > 0) {
      return direct;
    }

    const people = Number(setup.peopleCount) || 0;
    const perPerson = Number(setup.budgetPerPerson ?? setup.perPersonBudget) || 0;
    return people * perPerson;
  };

  const handleReset = () => {
    if (window.confirm('Are you sure you want to reset the trip? This will delete all expenses and setup data.')) {
      onReset();
      navigate('/setup');
    }
  };

  const handleEditSetup = () => {
    navigate('/setup');
  };

  const handleExportBackup = () => {
    const dataStr = JSON.stringify(data, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
    const now = new Date();
    const datePart = now instanceof Date && !isNaN(now.getTime()) ? now.toISOString().split('T')[0] : 'unknown_date';
    const exportFileDefaultName = `tripspend_backup_${datePart}.json`;

    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', exportFileDefaultName);
    linkElement.click();
  };

  const handleImportBackup = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const importedData = JSON.parse(e.target?.result as string);
        if (importedData.setup && Array.isArray(importedData.expenses)) {
          onImport(importedData.setup, importedData.expenses);
          alert('Backup restored successfully!');
          navigate('/');
        } else {
          alert('Invalid backup file format.');
        }
      } catch (err) {
        alert('Error parsing backup file.');
      }
    };
    reader.readAsText(file);
  };

  const handleShareSummary = () => {
    const totalBudget = getTotalBudget();
    const totalSpent = data.expenses.reduce((sum, exp) => sum + exp.amount, 0);
    const remaining = totalBudget - totalSpent;
    
    const categoryTotals = data.expenses.reduce((acc, exp) => {
      acc[exp.category] = (acc[exp.category] || 0) + exp.amount;
      return acc;
    }, {} as Record<string, number>);

    let summaryText = `📊 *TripSpend Summary*\n\n`;
    summaryText += `💰 Total Budget: ₹${totalBudget}\n`;
    summaryText += `💸 Total Spent: ₹${totalSpent}\n`;
    summaryText += `🏦 Remaining: ₹${remaining}\n\n`;
    summaryText += `*Category Breakdown:*\n`;
    Object.entries(categoryTotals).forEach(([cat, amt]) => {
      summaryText += `- ${cat}: ₹${amt}\n`;
    });
    
    summaryText += `\n_Generated by TripSpend_`;

    if (navigator.share) {
      navigator.share({
        title: 'TripSpend Summary',
        text: summaryText,
      }).catch(console.error);
    } else {
      navigator.clipboard.writeText(summaryText);
      alert('Summary copied to clipboard!');
    }
  };

  const handleShareSummaryImage = async () => {
    const totalBudget = getTotalBudget();
    const totalSpent = data.expenses.reduce((sum, exp) => sum + exp.amount, 0);
    const remaining = totalBudget - totalSpent;

    const canvas = document.createElement('canvas');
    canvas.width = 1080;
    canvas.height = 1350;
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      alert('Could not generate summary image.');
      return;
    }

    ctx.fillStyle = '#f8fafc';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = '#2563eb';
    ctx.fillRect(70, 70, canvas.width - 140, 220);
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 58px sans-serif';
    ctx.fillText('TripSpend Summary', 110, 180);

    ctx.fillStyle = '#0f172a';
    ctx.font = 'bold 46px sans-serif';
    ctx.fillText(`Budget: Rs ${totalBudget.toFixed(0)}`, 110, 380);
    ctx.fillText(`Spent: Rs ${totalSpent.toFixed(0)}`, 110, 460);
    ctx.fillText(`Remaining: Rs ${remaining.toFixed(0)}`, 110, 540);

    const categoryTotals = data.expenses.reduce((acc, exp) => {
      acc[exp.category] = (acc[exp.category] || 0) + exp.amount;
      return acc;
    }, {} as Record<string, number>);

    ctx.font = 'bold 38px sans-serif';
    ctx.fillText('Category Breakdown', 110, 660);
    ctx.font = '32px sans-serif';
    let lineY = 740;
    Object.entries(categoryTotals).forEach(([cat, amt]) => {
      ctx.fillText(`${cat}: Rs ${amt.toFixed(0)}`, 110, lineY);
      lineY += 64;
    });

    ctx.fillStyle = '#475569';
    ctx.font = '26px sans-serif';
    ctx.fillText(`Generated on ${new Date().toLocaleDateString()}`, 110, 1240);

    const blob = await new Promise<Blob | null>((resolve) => {
      canvas.toBlob((fileBlob) => resolve(fileBlob), 'image/png');
    });

    if (!blob) {
      alert('Could not generate summary image.');
      return;
    }

    const fileName = `tripspend_summary_${Date.now()}.png`;
    const file = new File([blob], fileName, { type: 'image/png' });
    const canShareFile = typeof navigator.canShare === 'function' && navigator.canShare({ files: [file] });

    if (Capacitor.isNativePlatform()) {
      try {
        const base64Data = await blobToBase64(blob);
        const writeResult = await Filesystem.writeFile({
          path: fileName,
          data: base64Data,
          directory: Directory.Cache,
        });

        await Share.share({
          title: 'TripSpend Summary Card',
          text: 'Trip summary card from TripSpend',
          files: [writeResult.uri],
          dialogTitle: 'Share summary card',
        });
        return;
      } catch (err) {
        console.error('Native share failed:', err);
      }
    }

    if (navigator.share && canShareFile) {
      try {
        await navigator.share({
          title: 'TripSpend Summary Card',
          text: 'Trip summary card from TripSpend',
          files: [file]
        });
        return;
      } catch (err) {
        if (err instanceof Error && err.name !== 'AbortError') {
          console.error('Share failed:', err.name, err.message);
        }
      }
    }

    const imageUrl = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = file.name;
    link.click();
    URL.revokeObjectURL(imageUrl);
  };

  return (
    <div className="page-shell">
      <div className="page-header">
        <h1 className="page-title">Settings</h1>
        <p className="page-subtitle">Manage your trip</p>
      </div>

      <div className="space-y-5">
        <motion.div className="card-premium rounded-3xl shadow-md overflow-hidden border-slate-200">
          <SettingItem 
            icon={<Edit3 className="w-5 h-5 text-blue-600" />}
            label="Edit Trip Setup"
            description="Change budget or people count"
            onClick={handleEditSetup}
          />
          <div className="h-px bg-slate-100 mx-6" />
          <SettingItem 
            icon={<Share2 className="w-5 h-5 text-emerald-600" />}
            label="Share Summary"
            description="Copy trip summary for WhatsApp"
            onClick={handleShareSummary}
          />
          <div className="h-px bg-slate-100 mx-6" />
          <SettingItem
            icon={<ImageIcon className="w-5 h-5 text-indigo-600" />}
            label="Share Summary Image"
            description="Generate summary card for WhatsApp"
            onClick={() => { void handleShareSummaryImage(); }}
          />
        </motion.div>

        <motion.div className="card-premium rounded-3xl shadow-md overflow-hidden border-slate-200">
          
          <div className="h-px bg-slate-100 mx-6" />
          <SettingItem 
            icon={<Users className="w-5 h-5 text-teal-600" />}
            label="Manage Members"
            description="Edit participant names"
            onClick={() => navigate('/members')}
          />
          <div className="h-px bg-slate-100 mx-6" />
          <SettingItem 
            icon={<Tag className="w-5 h-5 text-rose-600" />}
            label="Manage Categories"
            description="Add or edit expense categories"
            onClick={() => navigate('/categories')}
          />
        </motion.div>

        <motion.div className="card-premium rounded-3xl shadow-md overflow-hidden border-slate-200">
          <SettingItem 
            icon={<Download className="w-5 h-5 text-purple-600" />}
            label="Export Backup"
            description="Save all data to a JSON file"
            onClick={handleExportBackup}
          />
          <div className="h-px bg-slate-100 mx-6" />
          <SettingItem 
            icon={<Upload className="w-5 h-5 text-amber-600" />}
            label="Import Backup"
            description="Restore data from a JSON file"
            onClick={() => fileInputRef.current?.click()}
          />
          <input 
            type="file" 
            ref={fileInputRef} 
            className="hidden" 
            accept=".json" 
            onChange={handleImportBackup}
          />
        </motion.div>

        <motion.div className="card-premium rounded-3xl shadow-md overflow-hidden border-slate-200">
          <SettingItem 
            icon={<RotateCcw className="w-5 h-5 text-red-600" />}
            label="Reset Trip"
            description="Clear all data and start fresh"
            onClick={handleReset}
            danger
          />
        </motion.div>

        <motion.div className="bg-gradient-to-br from-slate-50 to-slate-100 p-7 rounded-3xl shadow-sm border border-slate-200">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 bg-blue-100 rounded-2xl flex items-center justify-center">
              <Info className="w-5 h-5 text-blue-600" />
            </div>
            <h3 className="font-bold text-slate-900 text-lg">About TripSpend</h3>
          </div>
          <p className="text-sm text-slate-600 leading-relaxed">
            TripSpend is a lightweight tool designed for group trip managers. 
            It helps you track a shared pool of money with receipts, voice input, and smart insights.
          </p>
          <p className="text-sm font-bold text-blue-700 mt-3 text-center w-full">Made by Amartya</p>
          <div className="mt-6 pt-6 border-t border-slate-200 text-center">
            <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Version 1.0.0</p>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

const SettingItem = ({ icon, label, description, onClick, danger }: { 
  icon: React.ReactNode, 
  label: string, 
  description: string, 
  onClick: () => void,
  danger?: boolean
}) => (
  <motion.button 
    whileHover={{ x: 4 }}
    onClick={onClick}
    className="w-full px-7 py-6 flex items-center gap-4 hover:bg-slate-50 transition-colors text-left group"
  >
    <div className={`w-11 h-11 rounded-2xl flex items-center justify-center flex-shrink-0 font-semibold ${danger ? 'bg-red-50' : 'bg-slate-100'}`}>
      {icon}
    </div>
    <div className="flex-grow min-w-0">
      <p className={`font-semibold text-base leading-tight ${danger ? 'text-red-700' : 'text-slate-900'}`}>{label}</p>
      <p className="text-xs text-slate-500 mt-0.5">{description}</p>
    </div>
    <ChevronRight className="w-5 h-5 text-slate-300 group-hover:text-slate-500 group-hover:translate-x-1 transition-all flex-shrink-0" />
  </motion.button>
);
